-- Add ATS scoring columns to resumes table
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score_completeness INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score_formatting INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score_keywords INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score_experience INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score_education INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_score_skills INTEGER DEFAULT 0;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_suggestions TEXT;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_strengths TEXT;
ALTER TABLE resumes ADD COLUMN IF NOT EXISTS ats_scored_at TIMESTAMP;
