import { Resume } from "@shared/api";

// Template-specific sample data
export const templateSampleData: Record<string, Resume> = {
  // Technology Templates
  "technology": {
    id: "sample-tech-1",
    personalInfo: {
      name: "Alex Johnson",
      title: "Senior Software Engineer",
      email: "alex.johnson@email.com",
      phone: "+1 (555) 123-4567",
      location: "San Francisco, CA",
      website: "alexjohnson.dev",
      linkedin: "linkedin.com/in/alexjohnson",
      github: "github.com/alexjohnson",
      avatar: "",
    },
    summary: "Experienced full-stack developer with 8+ years of experience building scalable web applications. Expertise in React, Node.js, and cloud technologies. Led development teams and delivered projects that increased user engagement by 40%.",
    objective: "Seeking a senior engineering role where I can leverage my expertise in modern web technologies to build innovative products that make a meaningful impact on users' lives.",
    skills: [
      { id: "1", name: "JavaScript", proficiency: 95, category: "Programming Languages", level: 95, yearsOfExperience: 8, isCore: true },
      { id: "2", name: "React", proficiency: 92, category: "Frontend Frameworks", level: 92, yearsOfExperience: 7, isCore: true },
      { id: "3", name: "Node.js", proficiency: 88, category: "Backend Technologies", level: 88, yearsOfExperience: 6, isCore: true },
      { id: "4", name: "TypeScript", proficiency: 90, category: "Programming Languages", level: 90, yearsOfExperience: 5, isCore: true },
      { id: "5", name: "Python", proficiency: 85, category: "Programming Languages", level: 85, yearsOfExperience: 4, isCore: false },
      { id: "6", name: "AWS", proficiency: 82, category: "Cloud Platforms", level: 82, yearsOfExperience: 5, isCore: true },
    ],
    experiences: [
      {
        id: "1",
        company: "TechCorp Inc.",
        position: "Senior Full Stack Developer",
        startDate: "2022-01",
        endDate: "Present",
        description: "Leading cross-functional development teams to deliver scalable web solutions for enterprise clients. Architected and implemented cloud-native microservices that significantly improved system reliability and performance.",
        technologies: ["React", "Node.js", "TypeScript", "AWS", "Docker"],
        location: "San Francisco, CA",
        employmentType: "Full-time",
        achievements: [
          "Led a team of 5 developers in delivering mission-critical platform features",
          "Implemented microservices architecture reducing system downtime by 60%",
          "Established coding standards and best practices across the engineering team",
        ],
      },
      {
        id: "2",
        company: "StartupXYZ",
        position: "Full Stack Developer",
        startDate: "2020-03",
        endDate: "2021-12",
        description: "Built the foundational technology stack for a fast-growing fintech startup. Developed customer-facing applications from concept to production, serving thousands of active users.",
        technologies: ["Vue.js", "Express", "MongoDB", "Stripe API", "Socket.io"],
        location: "San Francisco, CA",
        employmentType: "Full-time",
        achievements: [
          "Developed MVP from ground up, bringing product to market in 6 months",
          "Built responsive web application serving 10,000+ active users",
        ],
      },
    ],
    education: [
      {
        id: "1",
        institution: "University of California, Berkeley",
        degree: "Bachelor of Science",
        field: "Computer Science",
        startDate: "2014-09",
        endDate: "2018-05",
        location: "Berkeley, CA",
        gpa: "3.8",
      },
    ],
    projects: [
      {
        id: "1",
        title: "EcoTracker App",
        description: "Revolutionary carbon footprint tracking app with AI-powered recommendations for sustainable living. Featured in TechCrunch and gained 50k+ active users.",
        technologies: ["React Native", "Firebase", "Python", "TensorFlow", "Node.js"],
        startDate: "2023-01-01",
        endDate: "2023-06-01",
        url: "https://ecotracker.app",
        github: "github.com/alexjohnson/ecotracker",
      },
    ],
    upvotes: 127,
    rating: 4.8,
    isShortlisted: false,
    hasUpvoted: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
  },

  // Design Templates
  "design": {
    id: "sample-design-1",
    personalInfo: {
      name: "Maya Chen",
      title: "Creative Director & UX Designer",
      email: "maya.chen@design.com",
      phone: "+1 (555) 234-5678",
      location: "New York, NY",
      website: "mayachen.design",
      linkedin: "linkedin.com/in/mayachen",
      github: "",
      avatar: "",
    },
    summary: "Award-winning creative director with 10+ years of experience in digital design, branding, and user experience. Led design teams for Fortune 500 companies and startups, creating compelling visual narratives that drive engagement and conversion.",
    objective: "Seeking a creative leadership role where I can combine strategic thinking with innovative design to create meaningful brand experiences that resonate with diverse audiences.",
    skills: [
      { id: "1", name: "Adobe Creative Suite", proficiency: 98, category: "Design Tools", level: 98, yearsOfExperience: 10, isCore: true },
      { id: "2", name: "Figma", proficiency: 95, category: "Design Tools", level: 95, yearsOfExperience: 6, isCore: true },
      { id: "3", name: "Sketch", proficiency: 90, category: "Design Tools", level: 90, yearsOfExperience: 8, isCore: true },
      { id: "4", name: "Prototyping", proficiency: 92, category: "UX/UI", level: 92, yearsOfExperience: 8, isCore: true },
      { id: "5", name: "Brand Strategy", proficiency: 88, category: "Strategy", level: 88, yearsOfExperience: 7, isCore: true },
      { id: "6", name: "Typography", proficiency: 94, category: "Design", level: 94, yearsOfExperience: 10, isCore: true },
    ],
    experiences: [
      {
        id: "1",
        company: "Design Studio Pro",
        position: "Creative Director",
        startDate: "2021-06",
        endDate: "Present",
        description: "Leading a team of 12 designers and developers to create innovative digital experiences for global brands. Overseeing brand strategy, visual identity, and user experience design across multiple platforms.",
        technologies: ["Figma", "Adobe CC", "Principle", "InVision"],
        location: "New York, NY",
        employmentType: "Full-time",
        achievements: [
          "Increased client satisfaction scores by 45% through improved design processes",
          "Led rebranding projects for 3 Fortune 500 companies",
          "Mentored 8 junior designers, with 6 receiving promotions",
        ],
      },
      {
        id: "2",
        company: "Creative Agency NYC",
        position: "Senior UX Designer",
        startDate: "2018-03",
        endDate: "2021-05",
        description: "Designed user-centered digital experiences for e-commerce and SaaS platforms. Collaborated with product managers and developers to create intuitive interfaces that improved user engagement.",
        technologies: ["Sketch", "InVision", "Principle", "Zeplin"],
        location: "New York, NY",
        employmentType: "Full-time",
        achievements: [
          "Redesigned checkout flow resulting in 35% increase in conversions",
          "Created design system used across 15+ products",
        ],
      },
    ],
    education: [
      {
        id: "1",
        institution: "Parsons School of Design",
        degree: "Master of Fine Arts",
        field: "Design and Technology",
        startDate: "2012-09",
        endDate: "2014-05",
        location: "New York, NY",
        gpa: "3.9",
      },
    ],
    projects: [
      {
        id: "1",
        title: "EcoLiving Brand Identity",
        description: "Complete brand identity and digital experience design for sustainable living startup. Created cohesive visual language across web, mobile, and print materials.",
        technologies: ["Adobe CC", "Figma", "After Effects"],
        startDate: "2023-03-01",
        endDate: "2023-08-01",
        url: "https://ecoliving.com",
      },
    ],
    upvotes: 89,
    rating: 4.9,
    isShortlisted: false,
    hasUpvoted: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
  },

  // Management Templates
  "management": {
    id: "sample-mgmt-1",
    personalInfo: {
      name: "Robert Martinez",
      title: "VP of Engineering & Technology Leader",
      email: "robert.martinez@techcorp.com",
      phone: "+1 (555) 345-6789",
      location: "Austin, TX",
      website: "robertmartinez.tech",
      linkedin: "linkedin.com/in/robertmartinez",
      github: "",
      avatar: "",
    },
    summary: "Visionary technology executive with 15+ years of experience scaling engineering teams and delivering complex software solutions. Proven track record of leading digital transformations, building high-performance teams, and driving strategic initiatives that generate $50M+ in revenue.",
    objective: "Seeking a C-level technology leadership role where I can leverage my expertise in scaling engineering organizations and driving innovation to accelerate business growth and market expansion.",
    skills: [
      { id: "1", name: "Strategic Planning", proficiency: 95, category: "Leadership", level: 95, yearsOfExperience: 12, isCore: true },
      { id: "2", name: "Team Leadership", proficiency: 98, category: "Management", level: 98, yearsOfExperience: 15, isCore: true },
      { id: "3", name: "Product Strategy", proficiency: 90, category: "Strategy", level: 90, yearsOfExperience: 10, isCore: true },
      { id: "4", name: "Agile/Scrum", proficiency: 88, category: "Methodologies", level: 88, yearsOfExperience: 8, isCore: true },
      { id: "5", name: "Budget Management", proficiency: 85, category: "Finance", level: 85, yearsOfExperience: 10, isCore: true },
      { id: "6", name: "Stakeholder Management", proficiency: 92, category: "Communication", level: 92, yearsOfExperience: 12, isCore: true },
    ],
    experiences: [
      {
        id: "1",
        company: "TechCorp Global",
        position: "VP of Engineering",
        startDate: "2020-01",
        endDate: "Present",
        description: "Leading engineering organization of 120+ developers across 8 product teams. Responsible for technical strategy, architecture decisions, and delivery of enterprise software solutions serving 2M+ users globally.",
        technologies: ["Microservices", "AWS", "Kubernetes", "React", "Node.js"],
        location: "Austin, TX",
        employmentType: "Full-time",
        achievements: [
          "Scaled engineering team from 45 to 120+ developers while maintaining code quality",
          "Led digital transformation initiative resulting in 40% improvement in deployment frequency",
          "Implemented DevOps practices reducing production incidents by 65%",
          "Managed $15M annual engineering budget with 98% on-time project delivery",
        ],
      },
      {
        id: "2",
        company: "Innovation Labs Inc",
        position: "Director of Engineering",
        startDate: "2017-06",
        endDate: "2019-12",
        description: "Built and managed cross-functional engineering teams for multiple product lines. Established engineering culture, processes, and technical standards that supported rapid company growth from Series A to IPO.",
        technologies: ["Python", "React", "PostgreSQL", "Docker", "Jenkins"],
        location: "San Francisco, CA",
        employmentType: "Full-time",
        achievements: [
          "Hired and developed 35+ engineers across frontend, backend, and DevOps",
          "Established technical architecture supporting 10x user growth",
          "Led successful IPO technical due diligence process",
        ],
      },
    ],
    education: [
      {
        id: "1",
        institution: "Stanford University",
        degree: "Master of Business Administration",
        field: "Technology Management",
        startDate: "2015-09",
        endDate: "2017-06",
        location: "Stanford, CA",
        gpa: "3.8",
      },
      {
        id: "2",
        institution: "University of Texas at Austin",
        degree: "Bachelor of Science",
        field: "Computer Science",
        startDate: "2005-09",
        endDate: "2009-05",
        location: "Austin, TX",
        gpa: "3.7",
      },
    ],
    projects: [
      {
        id: "1",
        title: "Enterprise Platform Modernization",
        description: "Led complete modernization of legacy monolithic system to cloud-native microservices architecture. Project involved 50+ engineers and delivered 3x performance improvement.",
        technologies: ["Microservices", "AWS", "Kubernetes", "React", "GraphQL"],
        startDate: "2021-01-01",
        endDate: "2022-12-01",
      },
    ],
    upvotes: 156,
    rating: 4.7,
    isShortlisted: false,
    hasUpvoted: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
  },

  // Academic Templates
  "academic": {
    id: "sample-academic-1",
    personalInfo: {
      name: "Dr. Sarah Williams",
      title: "Associate Professor of Computer Science",
      email: "sarah.williams@university.edu",
      phone: "+1 (555) 456-7890",
      location: "Cambridge, MA",
      website: "sarahwilliams.edu",
      linkedin: "linkedin.com/in/drsarahwilliams",
      github: "github.com/drsarahwilliams",
      avatar: "",
    },
    summary: "Distinguished computer science researcher and educator with 12+ years of experience in artificial intelligence and machine learning. Published 45+ peer-reviewed papers, secured $2.3M in research funding, and mentored 25+ graduate students. Recognized expert in neural networks and deep learning applications.",
    objective: "Seeking a tenured professor position where I can continue advancing the field of AI research while inspiring the next generation of computer scientists through innovative teaching and mentorship.",
    skills: [
      { id: "1", name: "Machine Learning", proficiency: 98, category: "Research", level: 98, yearsOfExperience: 12, isCore: true },
      { id: "2", name: "Deep Learning", proficiency: 95, category: "Research", level: 95, yearsOfExperience: 8, isCore: true },
      { id: "3", name: "Python", proficiency: 92, category: "Programming", level: 92, yearsOfExperience: 15, isCore: true },
      { id: "4", name: "TensorFlow", proficiency: 90, category: "Frameworks", level: 90, yearsOfExperience: 6, isCore: true },
      { id: "5", name: "Research Methodology", proficiency: 96, category: "Academic", level: 96, yearsOfExperience: 12, isCore: true },
      { id: "6", name: "Grant Writing", proficiency: 88, category: "Academic", level: 88, yearsOfExperience: 10, isCore: true },
    ],
    experiences: [
      {
        id: "1",
        company: "Harvard University",
        position: "Associate Professor",
        startDate: "2019-09",
        endDate: "Present",
        description: "Teaching graduate and undergraduate courses in AI and machine learning. Leading research lab focused on neural network optimization and applications in healthcare. Supervising 8 PhD students and 12 master's students.",
        technologies: ["Python", "TensorFlow", "PyTorch", "CUDA", "R"],
        location: "Cambridge, MA",
        employmentType: "Full-time",
        achievements: [
          "Published 25 papers in top-tier conferences (ICML, NeurIPS, ICLR)",
          "Secured $1.5M NSF grant for healthcare AI research",
          "Received Excellence in Teaching Award 2022",
          "Graduated 12 PhD students, 8 now in faculty positions",
        ],
      },
      {
        id: "2",
        company: "MIT",
        position: "Assistant Professor",
        startDate: "2015-09",
        endDate: "2019-08",
        description: "Established independent research program in deep learning and computer vision. Taught courses in algorithms, machine learning, and AI ethics. Built collaborative relationships with industry partners.",
        technologies: ["Python", "MATLAB", "TensorFlow", "OpenCV"],
        location: "Cambridge, MA",
        employmentType: "Full-time",
        achievements: [
          "Published 20 papers with 1,200+ citations",
          "Received NSF CAREER Award ($800K)",
          "Developed new course curriculum adopted by 15+ universities",
        ],
      },
    ],
    education: [
      {
        id: "1",
        institution: "Stanford University",
        degree: "Ph.D.",
        field: "Computer Science",
        startDate: "2010-09",
        endDate: "2015-06",
        location: "Stanford, CA",
        gpa: "4.0",
      },
      {
        id: "2",
        institution: "MIT",
        degree: "Master of Science",
        field: "Computer Science",
        startDate: "2008-09",
        endDate: "2010-06",
        location: "Cambridge, MA",
        gpa: "3.9",
      },
    ],
    projects: [
      {
        id: "1",
        title: "Neural Network Optimization for Healthcare",
        description: "Multi-year research project developing efficient neural network architectures for medical image analysis. Collaboration with Massachusetts General Hospital resulting in FDA-approved diagnostic tool.",
        technologies: ["Python", "TensorFlow", "PyTorch", "CUDA", "Docker"],
        startDate: "2020-01-01",
        endDate: "2023-12-01",
        url: "https://healthcareai.harvard.edu",
      },
    ],
    upvotes: 234,
    rating: 4.9,
    isShortlisted: false,
    hasUpvoted: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
  },

  // Sales Templates
  "sales": {
    id: "sample-sales-1",
    personalInfo: {
      name: "Michael Thompson",
      title: "VP of Sales & Revenue Growth",
      email: "michael.thompson@salesforce.com",
      phone: "+1 (555) 567-8901",
      location: "Chicago, IL",
      website: "michaelthompson.sales",
      linkedin: "linkedin.com/in/michaelthompson",
      github: "",
      avatar: "",
    },
    summary: "Results-driven sales executive with 12+ years of experience building and scaling high-performance sales organizations. Consistently exceeded revenue targets by 25-40%, generated $150M+ in pipeline, and built teams that delivered record-breaking growth for SaaS and enterprise software companies.",
    objective: "Seeking a Chief Revenue Officer role where I can leverage my expertise in sales strategy, team development, and market expansion to drive exponential revenue growth and establish market leadership.",
    skills: [
      { id: "1", name: "Sales Strategy", proficiency: 96, category: "Sales", level: 96, yearsOfExperience: 12, isCore: true },
      { id: "2", name: "Team Leadership", proficiency: 94, category: "Management", level: 94, yearsOfExperience: 10, isCore: true },
      { id: "3", name: "Enterprise Sales", proficiency: 98, category: "Sales", level: 98, yearsOfExperience: 12, isCore: true },
      { id: "4", name: "CRM Management", proficiency: 90, category: "Technology", level: 90, yearsOfExperience: 8, isCore: true },
      { id: "5", name: "Negotiation", proficiency: 95, category: "Sales", level: 95, yearsOfExperience: 12, isCore: true },
      { id: "6", name: "Market Analysis", proficiency: 88, category: "Strategy", level: 88, yearsOfExperience: 10, isCore: true },
    ],
    experiences: [
      {
        id: "1",
        company: "SalesForce Technologies",
        position: "VP of Sales",
        startDate: "2020-03",
        endDate: "Present",
        description: "Leading North American sales organization of 45+ account executives and sales development representatives. Responsible for $85M annual revenue target across enterprise and mid-market segments.",
        technologies: ["Salesforce", "HubSpot", "Outreach", "ZoomInfo"],
        location: "Chicago, IL",
        employmentType: "Full-time",
        achievements: [
          "Exceeded annual revenue targets by 35% for 3 consecutive years",
          "Grew team from 25 to 45+ sales professionals",
          "Implemented sales methodology resulting in 28% increase in win rate",
          "Established partnerships generating $25M in additional pipeline",
        ],
      },
      {
        id: "2",
        company: "TechSolutions Inc",
        position: "Director of Sales",
        startDate: "2017-01",
        endDate: "2020-02",
        description: "Built and managed enterprise sales team for B2B SaaS platform. Developed go-to-market strategy for new product launches and established sales processes that scaled with company growth.",
        technologies: ["Salesforce", "Marketo", "LinkedIn Sales Navigator"],
        location: "Austin, TX",
        employmentType: "Full-time",
        achievements: [
          "Increased annual recurring revenue from $12M to $45M",
          "Achieved 127% of quota in final year",
          "Reduced sales cycle length by 40% through process optimization",
        ],
      },
    ],
    education: [
      {
        id: "1",
        institution: "Northwestern University",
        degree: "Master of Business Administration",
        field: "Marketing and Sales",
        startDate: "2014-09",
        endDate: "2016-06",
        location: "Evanston, IL",
        gpa: "3.8",
      },
      {
        id: "2",
        institution: "University of Illinois",
        degree: "Bachelor of Science",
        field: "Business Administration",
        startDate: "2008-09",
        endDate: "2012-05",
        location: "Urbana, IL",
        gpa: "3.6",
      },
    ],
    projects: [
      {
        id: "1",
        title: "Enterprise Sales Transformation",
        description: "Led comprehensive sales transformation initiative including CRM implementation, sales process redesign, and team restructuring. Resulted in 45% improvement in sales efficiency and $30M additional revenue.",
        technologies: ["Salesforce", "HubSpot", "Tableau", "Outreach"],
        startDate: "2021-01-01",
        endDate: "2022-06-01",
      },
    ],
    upvotes: 178,
    rating: 4.8,
    isShortlisted: false,
    hasUpvoted: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
  },

  // Marketing Templates
  "marketing": {
    id: "sample-marketing-1",
    personalInfo: {
      name: "Jessica Rodriguez",
      title: "Chief Marketing Officer & Growth Strategist",
      email: "jessica.rodriguez@growthco.com",
      phone: "+1 (555) 678-9012",
      location: "Los Angeles, CA",
      website: "jessicarodriguez.marketing",
      linkedin: "linkedin.com/in/jessicarodriguez",
      github: "",
      avatar: "",
    },
    summary: "Innovative marketing executive with 11+ years of experience driving brand growth and customer acquisition for B2B and B2C companies. Expert in digital marketing, content strategy, and performance marketing with a track record of generating 300%+ ROI and scaling marketing teams from startup to IPO.",
    objective: "Seeking a CMO role at a high-growth technology company where I can leverage my expertise in data-driven marketing and brand building to accelerate market expansion and establish category leadership.",
    skills: [
      { id: "1", name: "Digital Marketing", proficiency: 96, category: "Marketing", level: 96, yearsOfExperience: 11, isCore: true },
      { id: "2", name: "Content Strategy", proficiency: 94, category: "Marketing", level: 94, yearsOfExperience: 9, isCore: true },
      { id: "3", name: "Performance Marketing", proficiency: 92, category: "Marketing", level: 92, yearsOfExperience: 8, isCore: true },
      { id: "4", name: "Brand Management", proficiency: 90, category: "Marketing", level: 90, yearsOfExperience: 10, isCore: true },
      { id: "5", name: "Marketing Analytics", proficiency: 88, category: "Analytics", level: 88, yearsOfExperience: 7, isCore: true },
      { id: "6", name: "Team Leadership", proficiency: 93, category: "Management", level: 93, yearsOfExperience: 8, isCore: true },
    ],
    experiences: [
      {
        id: "1",
        company: "GrowthCo Technologies",
        position: "Chief Marketing Officer",
        startDate: "2021-01",
        endDate: "Present",
        description: "Leading marketing organization of 25+ professionals across brand, demand generation, content, and analytics. Responsible for driving customer acquisition, brand awareness, and revenue growth for B2B SaaS platform.",
        technologies: ["HubSpot", "Google Analytics", "Salesforce", "Marketo", "Tableau"],
        location: "Los Angeles, CA",
        employmentType: "Full-time",
        achievements: [
          "Increased qualified leads by 250% while reducing cost per acquisition by 40%",
          "Launched successful rebranding campaign resulting in 60% increase in brand awareness",
          "Built marketing team from 8 to 25+ professionals across all disciplines",
          "Achieved 320% ROI on marketing spend for 2 consecutive years",
        ],
      },
      {
        id: "2",
        company: "Digital Innovations Inc",
        position: "VP of Marketing",
        startDate: "2018-06",
        endDate: "2020-12",
        description: "Developed and executed comprehensive marketing strategy for fast-growing e-commerce platform. Led digital marketing, content creation, and customer lifecycle marketing initiatives.",
        technologies: ["Google Ads", "Facebook Ads", "Mailchimp", "Shopify", "Google Analytics"],
        location: "San Diego, CA",
        employmentType: "Full-time",
        achievements: [
          "Grew monthly active users from 50K to 500K in 18 months",
          "Implemented marketing automation reducing manual work by 70%",
          "Launched influencer marketing program generating $5M in attributed revenue",
        ],
      },
    ],
    education: [
      {
        id: "1",
        institution: "UCLA Anderson School of Management",
        degree: "Master of Business Administration",
        field: "Marketing and Strategy",
        startDate: "2016-09",
        endDate: "2018-06",
        location: "Los Angeles, CA",
        gpa: "3.9",
      },
      {
        id: "2",
        institution: "University of California, San Diego",
        degree: "Bachelor of Arts",
        field: "Communications",
        startDate: "2009-09",
        endDate: "2013-06",
        location: "San Diego, CA",
        gpa: "3.7",
      },
    ],
    projects: [
      {
        id: "1",
        title: "Omnichannel Brand Campaign",
        description: "Developed and executed integrated marketing campaign across digital, social, and traditional channels. Campaign generated 150M+ impressions and drove 40% increase in brand consideration.",
        technologies: ["Google Ads", "Facebook Ads", "LinkedIn Ads", "Programmatic", "TV/Radio"],
        startDate: "2022-03-01",
        endDate: "2022-12-01",
      },
    ],
    upvotes: 145,
    rating: 4.7,
    isShortlisted: false,
    hasUpvoted: false,
    createdAt: "2024-01-10T10:00:00Z",
    updatedAt: "2024-01-15T14:20:00Z",
  },
};

// Function to get sample data for a specific template
export function getTemplateSampleData(templateCategory: string): Resume {
  // Map template categories to sample data
  const categoryMap: Record<string, string> = {
    // Main categories
    'technology': 'technology',
    'design': 'design', 
    'management': 'management',
    'academic': 'academic',
    'sales': 'sales',
    'marketing': 'marketing',
    
    // Technology variations
    'tech-modern': 'technology',
    'tech-minimal': 'technology',
    'tech-senior': 'technology',
    'tech-fullstack': 'technology',
    'tech-devops': 'technology',
    'tech-mobile': 'technology',
    
    // Industry-specific mappings
    'healthcare-clinical': 'academic',
    'healthcare-admin': 'management',
    'healthcare-research': 'academic',
    'finance-analyst': 'management',
    'finance-advisor': 'sales',
    'finance-risk': 'management',
    'legal-corporate': 'management',
    'legal-litigation': 'sales',
    'legal-compliance': 'management',
    'education-k12': 'academic',
    'education-higher': 'academic',
    'education-administration': 'management',
    'nonprofit-program': 'management',
    'nonprofit-fundraising': 'sales',
    'nonprofit-advocacy': 'marketing',
    'consulting-strategy': 'management',
    'consulting-operations': 'management',
    'consulting-technology': 'technology',
  };

  const mappedCategory = categoryMap[templateCategory] || 'technology';
  return templateSampleData[mappedCategory] || templateSampleData.technology;
}

// Function to get all available sample data categories
export function getAvailableSampleCategories(): string[] {
  return Object.keys(templateSampleData);
}